### ISSUE TITLE
Wrong referrer in layout.osem.xml

### ISSUE THREAD

**Issue by hartho3** [joon-e/OSEM#2]
Hi Julian,

thank you for this great tool.
I just found a wrong referrer in the layout.osem.xml of the sosci-folder.

It must be <script src="osem.min.js"></script> instead of <script src="osem.js"></script>.

Cheers,
Thomas

**Comment by joon-e** [comment]
Hi Thomas,

thanks for pointing that out, it's fixed now.

Best regards,
Julian
